const game=document.querySelector('#game'),player=document.querySelector('#player'),overlay=document.querySelector('#overlay'),main=document.querySelector('#main'),scoreEl=document.querySelector('#score'),livesEl=document.querySelector('#lives'),levelEl=document.querySelector('#level'),msg=document.querySelector('#msg'),title=document.querySelector('#title'),text=document.querySelector('#text'),kicker=document.querySelector('#kicker'),sound=document.querySelector('#sound');
const TARGET=20,MAX=3;const state={mode:'idle',score:0,lives:MAX,level:1,x:0,keys:new Set(),items:[],last:0,spawn:0,raf:0,sound:true};let audio;
function beep(f=440,d=.06){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function hud(){scoreEl.textContent=state.score;livesEl.textContent=`${state.lives}/${MAX}`;levelEl.textContent=state.level}
function center(){state.x=game.clientWidth/2-player.offsetWidth/2;player.style.left=`${state.x}px`}
function clearItems(){state.items.forEach(i=>i.el.remove());state.items=[]}
function showMsg(t){msg.textContent=t;msg.classList.add('show');setTimeout(()=>msg.classList.remove('show'),700)}
function setOverlay(k,t,p,b){kicker.textContent=k;title.textContent=t;text.innerHTML=p;main.textContent=b;overlay.classList.remove('hidden')}
function start(){cancelAnimationFrame(state.raf);clearItems();Object.assign(state,{mode:'running',score:0,lives:MAX,level:1,spawn:0,last:performance.now()});state.keys.clear();hud();center();overlay.classList.add('hidden');game.focus();beep(520,.1);state.raf=requestAnimationFrame(loop)}
function pause(){if(state.mode!=='running')return;state.mode='paused';setOverlay('PROTOCOLO PAUSADO','Partida pausada','O sistema está congelado.','CONTINUAR')}
function resume(){if(state.mode!=='paused')return;state.mode='running';state.last=performance.now();overlay.classList.add('hidden');state.raf=requestAnimationFrame(loop)}
function finish(win){state.mode=win?'won':'lost';cancelAnimationFrame(state.raf);clearItems();beep(win?760:140,.2);setOverlay(win?'SISTEMA ESTABILIZADO':'FALHA DE INTEGRIDADE',win?'Sincronização concluída.':'Núcleo desconectado.',win?`Você alcançou <b>${state.score} pontos</b>.`:`Você chegou a <b>${state.score} pontos</b>.`,'JOGAR NOVAMENTE')}
function spawn(){const r=Math.random();let type='signal';if(r<.25+state.level*.015)type='hazard';else if(r>.93)type='boost';const el=document.createElement('div');el.className=`entity ${type}`;game.appendChild(el);const size=type==='boost'?28:24,x=14+Math.random()*Math.max(10,game.clientWidth-size-28),speed=150+state.level*32+Math.random()*70+(type==='hazard'?18:0);state.items.push({el,type,x,y:-35,size,speed})}
function hit(a,b){return !(a.right<b.left||a.left>b.right||a.bottom<b.top||a.top>b.bottom)}
function caught(type){if(type==='hazard'){state.lives--;showMsg('INTERFERÊNCIA DETECTADA');beep(120,.1);if(state.lives<=0){hud();finish(false);return}}else{state.score+=type==='boost'?3:1;showMsg(type==='boost'?'BOOST +3':'SINAL +1');beep(type==='boost'?700:520,.07);state.level=Math.min(5,1+Math.floor(state.score/5));if(state.score>=TARGET){hud();finish(true);return}}hud()}
function updatePlayer(dt){let dir=0;if(state.keys.has('arrowleft')||state.keys.has('a'))dir--;if(state.keys.has('arrowright')||state.keys.has('d'))dir++;state.x+=dir*360*dt;state.x=Math.max(0,Math.min(game.clientWidth-player.offsetWidth,state.x));player.style.left=`${state.x}px`}
function updateItems(dt){const pr=player.getBoundingClientRect();for(let i=state.items.length-1;i>=0;i--){const it=state.items[i];it.y+=it.speed*dt;it.el.style.transform=`translate(${it.x}px,${it.y}px)${it.type==='boost'?' rotate(45deg)':''}`;if(hit(it.el.getBoundingClientRect(),pr)){const type=it.type;it.el.remove();state.items.splice(i,1);caught(type);if(state.mode!=='running')return}else if(it.y>game.clientHeight+40){it.el.remove();state.items.splice(i,1)}}}
function loop(now){if(state.mode!=='running')return;const dt=Math.min((now-state.last)/1000,.033);state.last=now;updatePlayer(dt);state.spawn+=dt;if(state.spawn>=Math.max(.42,.88-state.level*.07)){state.spawn=0;spawn()}updateItems(dt);if(state.mode==='running')state.raf=requestAnimationFrame(loop)}
function moveTo(clientX){if(state.mode!=='running')return;const r=game.getBoundingClientRect();state.x=Math.max(0,Math.min(game.clientWidth-player.offsetWidth,clientX-r.left-player.offsetWidth/2));player.style.left=`${state.x}px`}
main.addEventListener('click',()=>state.mode==='paused'?resume():start());sound.addEventListener('click',()=>{state.sound=!state.sound;sound.textContent=state.sound?'🔊':'🔇';if(state.sound)beep(520)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','a','d'].includes(k)){e.preventDefault();state.keys.add(k)}if(k==='p'){e.preventDefault();state.mode==='running'?pause():state.mode==='paused'&&resume()}});addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));game.addEventListener('pointerdown',e=>moveTo(e.clientX));game.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.pressure>0)moveTo(e.clientX)});addEventListener('resize',()=>{state.x=Math.min(state.x,game.clientWidth-player.offsetWidth);player.style.left=`${Math.max(0,state.x)}px`});hud();center();